---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bucket
  namespace: flux-system
spec:
  interval: 10s
  path: ./app-740
  prune: true
  sourceRef:
    kind: Bucket
    name: 4-demo-source-minio-s3-bb-app
  targetNamespace: 4-demo
